### ISSUE TITLE
The two length checks gives wrong results if either string is empty

### ISSUE THREAD

**Issue by Fearswe** [uadnan/StringSimilarity#1]
```C#    
if ((source.Length == 0) || (target.Length == 0)) return 0;
if ((source.Length == 0) || (target.Length == 0)) return 0.0;
```

Those two checks should not exist as they invalidate this:
```C#
if (sourceWordCount == 0)
    return targetWordCount;
if (targetWordCount == 0)
   return sourceWordCount;
```
And results in incorrect values if one of the strings are empty.

Changing it from || (OR) to && (AND) would solve it, but is completely redundant since if both are 0 that's what gets returned anyways.

**Comment by uadnan** [comment]
Thanks @Fearswe for highlighting the issue.
